name: Test Workflows
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run CI workflows tests
        run: npm test src/__tests__/ci-workflows.test.ts
      - name: Run Docker builds tests
        run: npm test src/__tests__/docker-builds.test.ts
      - name: Run GitHub Actions tests
        run: npm test src/__tests__/github-actions.test.ts