name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - replit-agent
      - main
  workflow_dispatch:

# Prevent concurrent page deployments
concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and deploy to gh-pages
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "ERROR: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: dist/index.html not found"
            exit 1
          fi
          echo "✅ Build output verified successfully"
          ls -lah dist/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@4b09552dca4cd84bf1761447bcc0ebbfc9a5a5bb # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
