# DEPRECATED: This workflow is redundant with deploy-pages.yml
# 
# RECOMMENDATION: Delete this file and use deploy-pages.yml instead
# 
# Reasons for deprecation:
# 1. deploy-pages.yml covers the same functionality
# 2. deploy-pages.yml has better configuration (workflow_dispatch, concurrency control)
# 3. deploy-pages.yml uses GITHUB_TOKEN instead of custom PAT
# 4. Maintaining two similar workflows causes confusion
#
# If you need this workflow for a specific reason, here's the optimized version:

name: Build and Deploy (Legacy)

on:
  push:
    branches: ['replit-agent']
  workflow_dispatch:

# Prevent concurrent deployments
concurrency:
  group: gh-pages-legacy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    name: Build and deploy to gh-pages
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "ERROR: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: dist/index.html not found"
            exit 1
          fi
          echo "✅ Build output verified successfully"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
