name: Run Set Pages Source on Push (one-off)

on:
  push:
    branches: [ 'replit-agent' ]

permissions:
  contents: write

jobs:
  set-pages-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Pages source to gh-pages root
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAGES_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            try {
              await github.request('PATCH /repos/{owner}/{repo}/pages', {
                owner,
                repo,
                source: { branch: 'gh-pages', path: '/' }
              });
              core.info('Pages source set to gh-pages /');
            } catch (e) {
              core.setFailed(`Failed to set Pages source: ${e.message}`);
            }
