name: Set GitHub Pages Source

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/set-pages-source.yml'
      - 'dist/**'

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment happens at a time
concurrency:
  group: "pages-config-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  set-pages-source:
    name: Configure GitHub Pages source
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check if gh-pages branch exists
        id: check-branch
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'gh-pages'
              });
              return true;
            } catch (error) {
              if (error.status === 404) {
                return false;
              }
              throw error;
            }
      
      - name: Configure Pages
        if: steps.check-branch.outputs.result == 'true'
        uses: actions/configure-pages@v4
        with:
          enablement: true
