name: Set GitHub Pages Source

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'public/**'
      - '.github/workflows/set-pages-source.yml'

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment happens at a time
concurrency:
  group: "pages-config-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  set-pages-source:
    name: Configure GitHub Pages source
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.repository_owner == github.actor || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Configure GitHub Pages
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const response = await github.rest.repos.getPages({
              owner: context.repo.owner,
              repo: context.repo.repo
            }).catch(e => {
              if (e.status === 404) {
                console.log('ℹ️ GitHub Pages not configured yet');
                return { data: null };
              }
              throw e;
            });

            if (!response.data || response.data.source.branch !== 'gh-pages') {
              console.log('🔧 Setting GitHub Pages source to gh-pages branch');
              await github.rest.repos.createPagesSite({
                owner: context.repo.owner,
                repo: context.repo.repo,
                source: {
                  branch: 'gh-pages',
                  path: '/'
                }
              }).catch(e => {
                if (e.status === 409) {
                  console.log('ℹ️ GitHub Pages already exists, updating source');
                  return github.rest.repos.updateInformationAboutPagesSite({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    source: {
                      branch: 'gh-pages',
                      path: '/'
                    }
                  });
                }
                throw e;
              });
              console.log('✅ GitHub Pages source set to gh-pages branch');
            } else {
              console.log('✅ GitHub Pages already configured correctly');
            }
