name: Set Pages source (one-off)

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  set-pages-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check current Pages configuration
        id: check-pages
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.repos.getPages({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const isCorrectlyConfigured = response.data.source.branch === 'gh-pages' && 
                                          response.data.source.path === '/';
              
              core.info(`Current Pages config: ${JSON.stringify(response.data.source)}`);
              core.info(`Is correctly configured: ${isCorrectlyConfigured}`);
              
              return {
                exists: true,
                isCorrect: isCorrectlyConfigured,
                currentSource: response.data.source
              };
            } catch (error) {
              if (error.status === 404) {
                core.info('Pages is not configured yet');
                return { exists: false, isCorrect: false };
              }
              throw error;
            }
      - name: Check if gh-pages branch exists
        id: check-branch
        # Only check if Pages is not correctly configured
        if: fromJSON(steps.check-pages.outputs.result).isCorrect == false
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'gh-pages'
              });
              return true;
            } catch (error) {
              if (error.status === 404) {
                return false;
              }
              throw error;
            }

      - name: Configure Pages source to gh-pages branch
        if: fromJSON(steps.check-pages.outputs.result).isCorrect == false && steps.check-branch.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'gh-pages',
                path: '/'
              }
            });
            console.log('✅ Pages source set to gh-pages branch');

      - name: Create gh-pages branch if it doesn't exist
        if: fromJSON(steps.check-pages.outputs.result).isCorrect == false && steps.check-branch.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            // Get the default branch's latest commit
            const { data: defaultBranch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.payload.repository.default_branch
            });
            
            // Create gh-pages branch from default branch
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/gh-pages',
              sha: defaultBranch.commit.sha
            });
            
            console.log('✅ Created gh-pages branch');
            
            // Configure Pages source
            await github.rest.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'gh-pages',
                path: '/'
              }
            });
            
            console.log('✅ Pages source set to gh-pages branch');

      - name: Report completion
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pagesInfo = fromJSON('${{ steps.check-pages.outputs.result }}');
            if (pagesInfo.isCorrect) {
              core.info('✅ GitHub Pages is already correctly configured with gh-pages branch');
            } else {
              core.info('✅ GitHub Pages configuration has been updated');
            }
