name: Set Pages source (one-off)

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  set-pages-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check if gh-pages branch exists
        id: check-branch
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'gh-pages'
              });
              return true;
            } catch (error) {
              if (error.status === 404) {
                return false;
              }
              throw error;
            }

